### ISSUE TITLE
Make the switch to TypeScript

### ISSUE THREAD

**Issue by avanderhoorn** [Glimpse/Glimpse.Node.Prototype#10]
Before things get much bigger, lets make the switch to TypeScript. When we get a chance to breath we will be doing this on the client.

**Comment by philliphoff** [comment]
@mike-kaufman and I had a conversation about this before the holidays; we agreed we preferred to use TypeScript over raw JavaScript, but I argued that it didn't make sense for the immediate purposes of the prototype due to the (not insignificant, though hopefully one-time) costs of getting the infrastructure in place (the build process, transpilation, source maps, etc.). 

There are a number of related architectural discussion and decision needed once we promote this prototype to product.  What versions of Node do we want to support? E.g. while we might all be on the bleeding edge with 5.3.0, enterprises are still running 0.10/0.12 and probably will until their LTS ends in October for 0.10 and next year for 0.12.  This decision will limit what ES6 features we can take advantage of, even while using Babel or TypeScript.  Do we use Promise-based async patterns or more traditional callbacks? Do we try to support multiple web application frameworks (e.g. Express, Sails, Hapi, Koa) within the same package (requiring dependencies on all frameworks), or split things into multiple "adaptor" packages for each framework?

**Comment by avanderhoorn** [comment]
Status update: Agent has build infrastructure setup [x]. Issue can be closed after we can server infrastructure setup [ ].

**Comment by philliphoff** [comment]
We can now develop agent/server components using TypeScript.  (Note that we haven't ported all existing code to TypeScript; that isn't a priority at the moment and can be done whenever.  New code should probably all be done in TypeScript.)
