### ISSUE TITLE
Setup CI infrastructure

### ISSUE THREAD

**Issue by avanderhoorn** [Glimpse/Glimpse.Node.Prototype#40]
Lets get a basic CI up and running post getting the Unit Testing in so that at least we can start exercising those wheels and get a better test matrix covered. Most likely will use Travis.

**Comment by philliphoff** [comment]
I briefly looked into using Travis, but the guide mentioned that the person to set it up with a repo must be an administrator.  I'm happy to get this set up, but I don't know if I have all of the necessary permissions.

**Comment by nikmd23** [comment]
You should have the permissions you need now @philliphoff. Let me know if you need any other settings changed.

**Comment by philliphoff** [comment]
Thanks.  I'm currently playing with Travis integration in a personal fork of this repo.  When that appears to be working, I'll replicate it in this repo.  Travis doesn't seem to like the way we use Gulp to install/build the sub-packages, so I have to resort to writing a script to do so.  And Travis is currently not showing any of the build logs, so when it fails I just have to guess as to why.

**Comment by avanderhoorn** [comment]
Humm that sucks. Can you target it just to do the agent or server as a test to start with?

**Comment by philliphoff** [comment]
It looks like there was a Travis site issue that was keeping the logs from showing up.  Now that that's resolved, it looks like (at least some of) the build failures were due to TSD type definition installation hitting GitHub's rate limits, which appears to be a common issue with an easy fix.  I'll try it out in the morning and hopefully make more progress.

**Comment by avanderhoorn** [comment]
Great work!

**Comment by philliphoff** [comment]
Closed with #43.
